---

- hosts: all
  connection: local
  user: "{{ user }}"

  vars_files:
    - vars.yml

  roles:
    - { role: apps, tags: ['apps'] }
    - { role: bin, tags: ['bin'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    # - { role: osx, tags: ['osx'] }
    - { role: terminal, tags: ['terminal'] }
    - { role: vagrant, tags: ['vagrant'] }