- name: Copy dotfiles
  template: src="{{ item }}.j2" dest="{{ dotfiles_dir }}/.{{ item }}"
  ignore_errors: yes
  with_items:
    - gitconfig
    - bash_prompt
    - hushlogin
    - exports
    - gitattributes
    - curlrc
    - aliases
    - bash_profile
    - vimrc
    - inputrc
    - symfony2-autocomplete.bash

- name: Copy dotfiles
  copy: src="{{ item }}" dest="{{ dotfiles_dir }}/.{{ item }}"
  ignore_errors: yes
  with_items:
    - git-completion.bash
